# Generated by Django 5.1.6 on 2025-12-26 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                ("specializations", models.CharField(blank=True, max_length=255)),
                ("rating", models.FloatField(default=0.0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pandit_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
