# Generated by Django 5.1.6 on 2026-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Booking", "0002_alter_booking_pooja"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(default="unpaid", max_length=20),
        ),
    ]
