# Generated by Django 5.1.6 on 2026-01-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_booking_paid_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=1100),
        ),
    ]
